### ISSUE TITLE
Fix FOLIO indexing

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#873]
We're unable to index the instance with the hrid `a10362341`:

```
    /opt/app/indexer/searchworks_traject_indexer/shared/bundle/ruby/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/consumer.rb:252:in `rescue in block (4 levels) in each_message'
    Caused by
    KeyError: key not found: "statement"
    /opt/app/indexer/searchworks_traject_indexer/releases/20230508185150/lib/folio/mhld_builder.rb:70:in `fetch'
```

Here's a fragment of the holdings statements on the instance:

```
      "holdingsStatements"=>[{"staffNote"=>"Send to cataloging to receive and update holdings. Library keeps latest replacement volumes only. Latest volumes route to Grundfest", "statement"=>"v.1, 11"}],
      "statisticalCodeIds"=>[],
      "administrativeNotes"=>[],
      "effectiveLocationId"=>"5ecf146b-ce87-42f2-aa63-00d085e82d81",
      "permanentLocationId"=>"5ecf146b-ce87-42f2-aa63-00d085e82d81",
      "suppressFromDiscovery"=>false,
      "holdingsStatementsForIndexes"=>[],
      "holdingsStatementsForSupplements"=>[{"note"=>"Library keeps latest only", "staffNote"=>"Library keeps latest supplement only. Insert outdated to transfer shelf flag"}]}],
```

**Comment by jcoyne** [comment]
https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/folio/mhld_builder.rb#L70
